name: flutter_date_picker_number
description: A new Flutter package project.
version: 1.0.0
author: Marcin Butanowicz
homepage: m.butan@gmail.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: